[base]
package = ocean
env_name = puffer_hardmaze
policy_name = Policy
rnn_name = Recurrent

[vec]
num_envs = 8

[env]
num_envs = 4096
linear_speed = 4.0
# PI / 30
angular_speed = 0.10471973
radar_range = 150.0
range_finder_len = 60.0
frame_skip = 1
max_ticks = 1500

[train]
total_timesteps = 100_000_000
minibatch_size = 65536
