[base]
package = ocean
env_name = puffer_invest
policy_name = Policy
rnn_name = Recurrent

[vec]
num_envs = 8
seed = 42

[env]
num_envs = 2048
time_horizon = 512
T_min = 128
T_max = 1024
hurst = 0.1
process_type = fbm
liquidate = 1
# 0: one step liq, 1: linear liq
liq_type = 1
friction_coef = 0.01
friction_power = 2
reward_scale = 0.001
action_low = -5.0
action_high = 5.0
price_window_size = 32
prediction_len = 0
normalize_observations = true

# default params
[train]
total_timesteps = 500_000_000
minibatch_size = 65536
ent_coef = 1e-4
gae_lambda = 0.99
gamma = 0.999
learning_rate = 0.001
target_kl = 0.03
max_logratio = 12.0

[sweep]
metric = terminal_riskless


# sweeped params
# [train]
# adam_beta1 = 0.8603890121383637
# adam_beta2 = 0.99999
# adam_eps = 4.57977703868093e-09
# anneal_lr = true
# batch_size = auto
# bptt_horizon = 64
# checkpoint_interval = 200
# clip_coef = 0.31767553080887356
# ent_coef = 0.00012258578358954482
# gae_lambda = 0.99
# gamma = 0.999
# learning_rate = 0.004690138225547174
# max_grad_norm = 1.6848069476582097
# max_minibatch_size = 32768
# minibatch_size = 65536
# prio_alpha = 0.5705876587399061
# prio_beta0 = 0.9622848419082959
# seed = 42
# total_timesteps = 100_000_000
# update_epochs = 1
# vf_clip_coef = 0.1
# vf_coef = 4.805011878055362
# vtrace_c_clip = 0.14710707815498797
# vtrace_rho_clip = 2.2910961093964937
