[base]
package = ocean
env_name = puffer_invest
policy_name = Policy
rnn_name = Recurrent

[vec]
num_envs = 8

[env]
num_envs = 2048
time_horizon = 128
hurst = 0.1
process_type = fbm
liquidate = 1
# 0: one step liq, 1: linear liq
liq_type = 1
friction_coef = 0.00
friction_power = 2
price_window_size = 32

[train]
total_timesteps = 500_000_000
# seed = 42
minibatch_size = 65536

